{{- if .Values.postgresql.enabled }}
{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.postgresql.fullname" . }}
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: postgresql
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | toString | b64enc | quote }}
{{- end }}
{{- end }}
