blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & Answers
    url: https://github.com/shepherd44/airflow-helm-charts/discussions
    about: Ask and answer questions using GitHub Discussions