{{- if .Values.redis.enabled }}
{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.redis.fullname" . }}
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: redis
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | toString | b64enc | quote }}
{{- end }}
{{- end }}
