{{- if and .Values.dbCleanup.enabled .Values.dbCleanup.dropArchivedAfterDays }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-db-cleanup
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: db-cleanup
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  drop_archived.py: |
    {{- include "airflow.db_cleanup.drop_archived.py" . | nindent 4 }}
{{- end }}
