## this values file tests the git-sync sidecar
##
airflow:
  jwtSecret: "ci-only-not-a-real-secret"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/airflow-helm/charts.git"

    ## NOTE: an empty `branch` syncs the default branch of the remote repo
    branch: ""
    repoSubPath: "charts/airflow/examples"
